### ISSUE TITLE
home data - number of occupancies

### ISSUE THREAD

**Issue by gaozf0313** [JasmineZhihanQiu/ds4d#4]
Have you noticed that some of the homes' occupancy number didn't match the the number of columns of ages. How can we deal with it? Because we divide the homes into different type right? This may have impacts on which type the home belongs to.

**Comment by JasmineZhihanQiu** [comment]
It could consider other data in the same row, like if there are 2 people in home totally but have 3 age information, then you could change the the occupancy number in 3.

When there are 4 people in the home totally, but it only have 3 people in home then you can delete the data since we cannot guess the data of the fourth people.

We can build up our rule of the data cleaning.
